###
# Builder container
###
FROM node:18-alpine AS node
FROM golang:1.19-alpine AS builder

COPY --from=node /usr/lib /usr/lib
COPY --from=node /usr/local/share /usr/local/share
COPY --from=node /usr/local/lib /usr/local/lib
COPY --from=node /usr/local/include /usr/local/include
COPY --from=node /usr/local/bin /usr/local/bin
COPY --from=node /opt /opt

ARG tags=docker
ARG version=devel
ARG sha=devel
ARG goproxy
ARG npmproxy
ARG swagversion=1.8.10

ENV CGOENABLED=1 \
    YARN_REGISTRY=$npmproxy \
    GOPROXY=$goproxy

RUN go version && \
    apk add --update --no-cache gcc musl-dev git curl make gcc g++ && \
    mkdir /pufferpanel && \
    wget https://github.com/swaggo/swag/releases/download/v${swagversion}/swag_${swagversion}_Linux_x86_64.tar.gz && \
    mkdir -p ~/go/bin && \
    tar -zxf swag*.tar.gz -C ~/go/bin && \
    rm -rf swag*.tar.gz

WORKDIR /build/pufferpanel

COPY go.mod go.sum ./
RUN go mod download && go mod verify

COPY . .

RUN cd client && \
    rm -f frontend/src/lang && \
    ln -s ../../src/lang frontend/src/lang && \
    yarn install && \
    yarn build && \
    ~/go/bin/swag init -o web/swagger -g web/loader.go && \
    go build -v -buildvcs=false -tags "$tags" -o /pufferpanel/templatetester github.com/pufferpanel/pufferpanel/v3/templatetester && \
    mv assets/email /pufferpanel/email

###
# Generate final image
###

FROM ubuntu:20.04

ENV DEBIAN_FRONTEND=noninteractive

RUN apt update && \
    apt install -y zip unzip tar git wget curl xz-utils dirmngr gnupg apt-transport-https ca-certificates software-properties-common

RUN apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF && \
    apt-add-repository 'deb https://download.mono-project.com/repo/ubuntu stable-focal main' && \
    dpkg --add-architecture i386 && \
    curl -fsSL https://deb.nodesource.com/setup_18.x | bash -

RUN apt update && \
    apt install -y nodejs lib32gcc1 libstdc++6 mono-complete && \
    apt-get clean

RUN useradd pufferpanel && \
    mkdir /home/pufferpanel && \
    chown -R pufferpanel:pufferpanel /home/pufferpanel


COPY --from=builder /pufferpanel /pufferpanel
WORKDIR /pufferpanel

USER pufferpanel

ENTRYPOINT ["/pufferpanel/templatetester"]
CMD ["--gitref=refs/heads/v2.6"]