#!/usr/bin/env php

<?php


echo "Enter MySQL information to update the panel\n";

echo "Host [localhost]: ";
$host = trim(fgets(STDIN));
if (strlen($host) == 0) {
    $host = 'localhost';
}

echo "Port [3306]: ";
$port = trim(fgets(STDIN));
if (strlen($port) == 0) {
    $port = '3306';
}

$db='pufferpanel';

echo "User [root]: ";
$user = trim(fgets(STDIN));
if (strlen($user) == 0) {
    $user = 'root';
}

function hide_term() {
    if (strtoupper(substr(PHP_OS, 0, 3)) !== 'WIN')
        system('stty -echo');
}

function restore_term() {
    if (strtoupper(substr(PHP_OS, 0, 3)) !== 'WIN')
        system('stty echo');
}

hide_term();
do {
    echo "Password: ";
    $pass = rtrim(fgets(STDIN), PHP_EOL);
} while (strlen($pass) == 0);
restore_term();

//$config = json_decode(file_get_contents(__DIR__ . '/../config.json'));
//$user = $config->mysql->username;
//$pass = $config->mysql->password;
//$host = $config->mysql->host;
//$db = $config->mysql->database;
//$port = $config->mysql->port;

echo 'Will open a connection to ' . $host . ':' . $port . ' using ' . $user;
echo "\n";

//Assume old version, if this fails we do not care
$query = 'ALTER TABLE nodes ADD COLUMN docker TINYINT(4) NOT NULL DEFAULT \'1\'';
$cmd = sprintf('mysql -h %s -P %d -u %s --password=%s -D %s -e "%s"', $host, $port, $user, escapeshellcmd($pass), $db, $query);
system($cmd);

echo "If above failed with 'Duplicate column', that error may be ignored\n";

//Add changes to 0.9
$query = 'CREATE TABLE IF NOT EXISTS oauth_clients (
	id INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
	client_id CHAR(16) NOT NULL ,
	client_secret CHAR(64) NOT NULL ,
	user_id INT(10) UNSIGNED NOT NULL,
	server_id INT(10) UNSIGNED NOT NULL,
	scopes VARCHAR(1000) NOT NULL DEFAULT \'\' ,
	name VARCHAR(128) NOT NULL ,
	description VARCHAR(1024) NOT NULL DEFAULT \'\' ,
	PRIMARY KEY (id),
	INDEX FK_oauth_clients_users (user_id),
	INDEX FK_oauth_clients_servers (server_id),
	INDEX client_id (client_id)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS oauth_access_tokens (
  access_token char(128) COLLATE utf8_unicode_ci NOT NULL,
  client_id int(10) unsigned NOT NULL,
  expiretime timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  scopes varchar(1000) COLLATE utf8_unicode_ci NOT NULL DEFAULT \'\',
  PRIMARY KEY (access_token),
  UNIQUE KEY access_token (access_token)
) ENGINE=InnoDB; ';

$cmd = sprintf('mysql -h %s -P %d -u %s --password=%s -D %s -e "%s"', $host, $port, $user, escapeshellcmd($pass), $db, $query);
system($cmd);

echo "\n";