# Last Modified: Sat Jun 14 14:12:25 2025
abi <abi/3.0>,

include <tunables/global>

/usr/sbin/pufferpanel {
  include <abstractions/base>

  /etc/pufferpanel/* rw,
  /var/lib/pufferpanel/* rw,
  /var/log/pufferpanel/* rw,

  capability setgid,
  capability setuid,
  capability sys_admin,

  mount options=(rprivate, rw) -> /,

  /usr/sbin/pufferpanel mr,
  /usr/bin/* ux,
  owner /proc/*/gid_map w,
  owner /proc/*/setgroups w,
  owner /proc/*/uid_map w,
}
