name: Build Core
on:
  push:
    branches:
      - v3
    tags:
      - v3.*
    paths-ignore:
      - '.github/workflows/tester.yml'
      - '.github/workflows/run-template-tester.yml'
      - '.github/workflows/formatter.yml'
  pull_request:
    branches:
      - v3
    paths-ignore:
      - 'client/frontend/src/lang/**.json'

env:
  SWAG_VERSION: "1.16.4"
  NODE_VERSION: "22"
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

concurrency:
  group: ${{ github.event_name}}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-shared:
    name: Build Shared Objects
    runs-on: ubuntu-latest
    if: "startsWith(github.ref, 'refs/tags/v') || !contains(github.event.head_commit.message, '[skip]')"

    timeout-minutes: 10

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'yarn'
          cache-dependency-path: 'client/yarn.lock'

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'

      - name: Restore Go BIN
        id: restore-go-bin
        uses: actions/cache@v4
        with:
          path: |
            ~/go/bin
          key: ${{ runner.os }}-swag-${{ env.SWAG_VERSION }}
          restore-keys: |
            ${{ runner.os }}-swag-

      - name: Download Go Binaries
        if: steps.restore-go-bin.outputs.cache-hit != 'true'
        run: |
          go install github.com/swaggo/swag/cmd/swag@latest

      - name: Download Go modules
        run: |
          go mod download

      - name: Generate Swagger Docs
        run: |
          ~/go/bin/swag init --pd --md . -o web/swagger -g web/loader.go

      - name: yarn install, build
        run: |
          npm install -g yarn
          yarn install
          env VITE_CHECK_ENV="true" yarn build
        env:
          CI: true
        working-directory: client

      - name: Upload Swagger docs
        uses: actions/upload-artifact@v4
        with:
          name: pufferpanel_swagger
          path: |
            web/swagger/swagger.json
            web/swagger/swagger.yaml
          if-no-files-found: error

      - name: Set CurseForge Key
        env:
          secret_set: ${{ secrets.CURSEFORGE_CODE }}
        if: ${{ env.secret_set != '' }}
        run: |
          echo '${{ secrets.CURSEFORGE_CODE }}' > config/curseforge.go

      - name: Generate folders and remove excess files
        run: |
          rm -rf .git .github web/swagger/swagger.json web/swagger/swagger.yaml build-artifacts/client/frontend/dist/*.map

      - name: Generate job artifact
        uses: actions/upload-artifact@v4
        with:
          name: pufferpanel_build_artifact
          path: ${{ github.workspace }}
          if-no-files-found: error
          retention-days: 1

  build-linux-amd64-binaries:
    name: Build Binaries - Linux AMD64
    runs-on: ubuntu-latest
    needs: [ 'build-shared' ]

    timeout-minutes: 10
    env:
      VERSION:

    steps:
      - name: Get the version
        run: echo "VERSION=0.0.${GITHUB_RUN_NUMBER}" >> $GITHUB_ENV

      - name: Get the version
        if: startsWith(github.ref, 'refs/tags/v')
        run: echo "VERSION=${GITHUB_REF/refs\/tags\/v/}" >> $GITHUB_ENV

      - name: Download APT packages
        run: |
          sudo apt-get update
          sudo apt-get install --download-only -y rpm

      - name: APT Install
        run: |
          sudo apt-get install -y rpm

      - uses: actions/download-artifact@v4
        with:
          name: pufferpanel_build_artifact

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'

      - name: Build Linux
        run: |
          go build -o build-artifacts/pufferpanel -ldflags "-X 'github.com/pufferpanel/pufferpanel/v3.Hash=${{ github.sha }}' -X 'github.com/pufferpanel/pufferpanel/v3.Version=${{ env.VERSION }}'" -v github.com/pufferpanel/pufferpanel/v3/cmd
          go test -v ./...
        env:
          GOOS: linux
          GOARCH: amd64

      - name: Set up build folder
        run: |
          mkdir -p DEBBUILD/usr/sbin DEBBUILD/var/www/pufferpanel RPMBUILD/var/www/pufferpanel
          mkdir -p DEBBUILD/var/log/pufferpanel RPMBUILD/var/log/pufferpanel
          mkdir -p DEBBUILD/etc/pufferpanel DEBBUILD/lib/systemd/system DEBBUILD/etc/apparmor.d/
          mkdir -p DEBBUILD/var/lib/pufferpanel/binaries RPMBUILD/var/lib/pufferpanel
          cp config.linux.json DEBBUILD/etc/pufferpanel/config.json
          cp build-artifacts/pufferpanel DEBBUILD/usr/sbin/pufferpanel
          cp systemd/servicefiles/pufferpanel.service DEBBUILD/lib/systemd/system/pufferpanel.service
          cp systemd/servicefiles/apparmor.conf DEBBUILD/etc/apparmor.d/pufferpanel

      - name: Build Package DEB AMD64
        id: debamd64
        uses: pufferpanel/build-deb@master
        with:
          data-folder: DEBBUILD
          package: pufferpanel
          version: ${{ env.VERSION }}
          license: Apache 2.0
          architecture: amd64
          maintainer: PufferPanel <dev@pufferpanel.com>
          homepage: https://pufferpanel.com
          description: Game management server panel
          before-install: systemd/scripts/preinstall.sh
          after-install: systemd/scripts/postinstall.sh
          before-upgrade: systemd/scripts/preupgrade.sh
          after-upgrade: systemd/scripts/postupgrade.sh
          before-remove: systemd/scripts/preremove.sh
          after-remove: systemd/scripts/postremove.sh
          after-purge: systemd/scripts/purge.sh
          extra-dpkg-args: '-Zxz'
          suggested-packages: |
            lib32gcc1

      - name: Build Package RPM AMD64
        id: rpmamd64
        uses: pufferpanel/build-rpm@master
        with:
          package: pufferpanel
          version: ${{ env.VERSION }}
          license: Apache 2.0
          architecture: x86_64
          maintainer: PufferPanel <dev@pufferpanel.com>
          website: https://pufferpanel.com
          summary: Game management server panel
          before-install: systemd/scripts/preinstall.sh
          after-install: systemd/scripts/postinstall.sh
          before-upgrade: systemd/scripts/preupgrade.sh
          after-upgrade: systemd/scripts/postupgrade.sh
          before-remove: systemd/scripts/preremove.sh
          after-remove: systemd/scripts/postremove.sh
          after-purge: systemd/scripts/purge.sh
          user: pufferpanel
          group: pufferpanel
          files: |
            build-artifacts/pufferpanel:/usr/sbin/pufferpanel
            config.linux.json:/etc/pufferpanel/config.json
            systemd/servicefiles/pufferpanel.service:/lib/systemd/system/pufferpanel.service
            RPMBUILD/var/lib/pufferpanel:/var/lib/pufferpanel
            RPMBUILD/var/log/pufferpanel:/var/log/pufferpanel
            RPMBUILD/var/www/pufferpanel:/var/www/pufferpanel
          config: |
            /etc/pufferpanel/config.json:noreplace
          suggested-packages: |
            glibc.i686
            libstdc++.i686

      - name: Publish Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: pufferpanel_${{ env.VERSION }}_linux_amd64
          path: build-artifacts/

      - name: Publish Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: pufferpanel_${{ env.VERSION }}_amd64.deb
          path: pufferpanel_${{ env.VERSION }}_amd64.deb

      - name: Publish Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: pufferpanel-${{ env.VERSION }}-1.x86_64.rpm
          path: ${{ steps.rpmamd64.outputs.file }}

  build-linux-arm64-binaries:
    name: Build Binaries - Linux ARM64
    runs-on: ubuntu-latest
    needs: [ 'build-shared' ]

    timeout-minutes: 10
    env:
      VERSION:

    steps:
      - name: Get the version
        run: echo "VERSION=0.0.${GITHUB_RUN_NUMBER}" >> $GITHUB_ENV

      - name: Get the version
        if: startsWith(github.ref, 'refs/tags/v')
        run: echo "VERSION=${GITHUB_REF/refs\/tags\/v/}" >> $GITHUB_ENV

      - uses: actions/download-artifact@v4
        with:
          name: pufferpanel_build_artifact

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'

      - name: Download APT packages
        run: |
          sudo apt-get update
          sudo apt-get install --download-only -y gcc-aarch64-linux-gnu

      - name: APT Install
        run: |
          sudo apt-get install -y gcc-aarch64-linux-gnu

      - name: Build ARM64
        run: |
          go build -o build-artifacts/pufferpanel -ldflags "-X 'github.com/pufferpanel/pufferpanel/v3.Hash=${{ github.sha }}' -X 'github.com/pufferpanel/pufferpanel/v3.Version=${{ env.VERSION }}'" -v github.com/pufferpanel/pufferpanel/v3/cmd
        env:
          GOOS: linux
          GOARCH: arm64
          CC: aarch64-linux-gnu-gcc
          CGO_ENABLED: 1

      - name: Set up build folder
        run: |
          mkdir -p DEBBUILD/usr/sbin DEBBUILD/var/www/pufferpanel RPMBUILD/var/www/pufferpanel
          mkdir -p DEBBUILD/var/log/pufferpanel RPMBUILD/var/log/pufferpanel
          mkdir -p DEBBUILD/etc/pufferpanel DEBBUILD/lib/systemd/system/ DEBBUILD/etc/apparmor.d
          mkdir -p DEBBUILD/var/lib/pufferpanel/binaries RPMBUILD/var/lib/pufferpanel
          cp config.linux.json DEBBUILD/etc/pufferpanel/config.json
          cp build-artifacts/pufferpanel DEBBUILD/usr/sbin/pufferpanel
          cp systemd/servicefiles/pufferpanel.service DEBBUILD/lib/systemd/system/pufferpanel.service
          cp systemd/servicefiles/apparmor.conf DEBBUILD/etc/apparmor.d/pufferpanel

      - name: Build Package DEB ARM64
        id: debarm64
        uses: pufferpanel/build-deb@master
        with:
          data-folder: DEBBUILD
          package: pufferpanel
          version: ${{ env.VERSION }}
          license: Apache 2.0
          architecture: arm64
          maintainer: PufferPanel <dev@pufferpanel.com>
          homepage: https://pufferpanel.com
          description: Game management server panel
          before-install: systemd/scripts/preinstall.sh
          after-install: systemd/scripts/postinstall.sh
          before-upgrade: systemd/scripts/preupgrade.sh
          after-upgrade: systemd/scripts/postupgrade.sh
          before-remove: systemd/scripts/preremove.sh
          after-remove: systemd/scripts/postremove.sh
          after-purge: systemd/scripts/purge.sh
          extra-dpkg-args: '-Zxz'

      - name: Build Package RPM ARM64
        id: rpmarm64
        uses: pufferpanel/build-rpm@master
        with:
          package: pufferpanel
          version: ${{ env.VERSION }}
          license: Apache 2.0
          architecture: aarch64
          maintainer: PufferPanel <dev@pufferpanel.com>
          website: https://pufferpanel.com
          summary: Game management server panel
          before-install: systemd/scripts/preinstall.sh
          after-install: systemd/scripts/postinstall.sh
          before-upgrade: systemd/scripts/preupgrade.sh
          after-upgrade: systemd/scripts/postupgrade.sh
          before-remove: systemd/scripts/preremove.sh
          after-remove: systemd/scripts/postremove.sh
          after-purge: systemd/scripts/purge.sh
          user: pufferpanel
          group: pufferpanel
          files: |
            build-artifacts/pufferpanel:/usr/sbin/pufferpanel
            config.linux.json:/etc/pufferpanel/config.json
            systemd/servicefiles/pufferpanel.service:/lib/systemd/system/pufferpanel.service
            RPMBUILD/var/lib/pufferpanel:/var/lib/pufferpanel
            RPMBUILD/var/log/pufferpanel:/var/log/pufferpanel
            RPMBUILD/var/www/pufferpanel:/var/www/pufferpanel
          config: |
            /etc/pufferpanel/config.json:noreplace

      - name: Publish Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: pufferpanel_${{ env.VERSION }}_linux_arm64
          path: build-artifacts

      - name: Publish Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: pufferpanel_${{ env.VERSION }}_arm64.deb
          path: pufferpanel_${{ env.VERSION }}_arm64.deb

      - name: Publish Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: pufferpanel-${{ env.VERSION }}-1.aarch64.rpm
          path: ${{ steps.rpmarm64.outputs.file }}

  cleanup:
    runs-on: ubuntu-latest
    name: "Cleanup"

    needs: [ build-shared, build-docker-image-base, build-linux-amd64-binaries, build-linux-arm64-binaries, release ]

    continue-on-error: true

    steps:
      - name: Delete artifacts
        uses: geekyeggo/delete-artifact@v5
        with:
          name: pufferpanel_build_artifact

  build-docker-image-base:
    name: "Build Docker image"
    if: "github.event_name != 'pull_request' && (startsWith(github.ref, 'refs/tags/v') || !contains(github.event.head_commit.message, '[skip]'))"
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    environment: ${{ startsWith(github.ref, 'refs/tags/') && 'Release' || 'Development' }}

    timeout-minutes: 15

    env:
      REGISTRY: ${{ vars.REGISTRY != 'docker.com' && vars.REGISTRY || '' }}
      REGISTRY_USERNAME: ${{ vars.REGISTRY == 'ghcr.io' && github.actor || secrets.REGISTRY_USERNAME }}
      REGISTRY_PASSWORD: ${{ vars.REGISTRY == 'ghcr.io' && secrets.GITHUB_TOKEN || secrets.REGISTRY_PASSWORD }}
      VERSION:

    steps:
      - name: Get the version
        run: echo "VERSION=0.0.${GITHUB_RUN_NUMBER}" >> $GITHUB_ENV

      - name: Get the version
        if: startsWith(github.ref, 'refs/tags/v')
        run: echo "VERSION=${GITHUB_REF/refs\/tags\/v/}" >> $GITHUB_ENV

      - name: Ensure mask
        id: values
        run: |
          echo "::add-mask::$REGISTRY_USERNAME"
          echo "::add-mask::$REGISTRY_PASSWORD"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        if: env.REGISTRY_USERNAME != '' && env.REGISTRY != ''
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ env.REGISTRY_USERNAME }}
          password: ${{ env.REGISTRY_PASSWORD }}

      - name: Login to DockerHub
        if: env.REGISTRY_USERNAME != '' && env.REGISTRY == ''
        uses: docker/login-action@v3
        with:
          username: ${{ env.REGISTRY_USERNAME }}
          password: ${{ env.REGISTRY_PASSWORD }}

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            name=${{ vars.REGISTRY != 'docker.com' && format('{0}/', env.REGISTRY) || '' }}${{ env.IMAGE_NAME }},enable=${{ vars.REGISTRY != 'docker.com' }}
            name=${{ env.IMAGE_NAME }},enable=${{ vars.REGISTRY == 'docker.com' }}
          tags: |
            type=ref,prefix=branch-,event=branch
            type=semver,pattern={{version}}

      - name: Check out code into the Go module directory
        uses: actions/checkout@v4

      - name: Build and push Docker image
        id: build-and-push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile
          push: ${{ github.event_name != 'pull_request' && env.REGISTRY_USERNAME != '' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            sha=${{ github.sha }}
            version=${{ env.VERSION }}
            curseforgeKey=${{ secrets.CURSEFORGE_KEY }}
          platforms: linux/amd64,linux/arm64

  release:
    name: "Deployment"
    runs-on: ubuntu-latest
    needs:
      - build-docker-image-base
      - build-linux-amd64-binaries
      - build-linux-arm64-binaries
    permissions:
      contents: write
    environment: ${{ startsWith(github.ref, 'refs/tags/v') && 'Release' || 'Development' }}
    if: "github.event_name != 'pull_request'"

    steps:
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3'

      - name: Install gems
        run: |
          gem install --no-doc package_cloud

      - uses: actions/download-artifact@v4
        with:
          pattern: pufferpanel_*

      - uses: actions/download-artifact@v4
        with:
          pattern: pufferpanel-*.rpm

      - name: Push to repo
        env:
          PACKAGECLOUD_TOKEN: ${{ secrets.PACKAGECLOUD_TOKEN }}
        run: |
          package_cloud push ${{ vars.PACKAGECLOUD_REPO }}/any/any */pufferpanel_*_amd64.deb 
          package_cloud push ${{ vars.PACKAGECLOUD_REPO }}/any/any */pufferpanel_*_arm64.deb 
          package_cloud push ${{ vars.PACKAGECLOUD_REPO }}/rpm_any/rpm_any */pufferpanel-*.x86_64.rpm 

      - name: Create Release
        id: create_release
        if: "startsWith(github.ref, 'refs/tags/v')"
        uses: softprops/action-gh-release@v2
        with:
          draft: false
          prerelease: ${{ contains(github.ref, '-rc') || contains(github.ref, '-beta') || contains(github.ref, '-alpha') }}
          files: |
            pufferpanel_*_linux_amd64
            pufferpanel_*_linux_arm64
            pufferpanel_*_windows_amd64
            */*.rpm
            */*.deb
