name: Run Tool - Tester
on:
  repository_dispatch:
    types:
      - template-tester

jobs:
  run-tester:
    name: Run Tool
    runs-on: template-tester-${{ matrix.arch }}
    permissions:
      packages: read

    strategy:
      matrix:
        template: ${{ github.event.client_payload.templates }}
        arch: [ amd64 ]
      fail-fast: false

    steps:
      - name: Download assets
        uses: actions/download-artifact@v4
        with:
          name: tool-binaries
          run-id: '${{ github.event.client_payload.run_id }}'

      - name: Run
        run: |
          chmod +x pufferpanel_* templatetester_*
          ./templatetester_${{ matrix.arch }} --require=${{ matrix.template }} --binary=./pufferpanel_${{ matrix.arch }}