name: Run Tool - Tester
on:
  repository_dispatch:
    types:
      - template-tester

jobs:
  run-tester:
    name: Run Tool
    runs-on: [ "template-tester", "${{ matrix.arch }}", "${{ matrix.os }}" ]
    permissions:
      packages: read

    strategy:
      matrix:
        template: ${{ github.event.client_payload.templates }}
        arch: [ x64, arm64 ]
        os: [ linux ]
      fail-fast: false

    steps:
      - name: Download assets
        uses: actions/download-artifact@v4
        with:
          name: tool-binaries
          run-id: '${{ github.event.client_payload.run_id }}'
          github-token: ${{ secrets.ACCESS_DOWNLOAD_PAT }}

        # We will only install deps if this is a "host", we will not do it for docker templates
      - name: Install global deps
        if: ${{ ! endsWith(matrix.template, '-docker') }}
        run: |
          sudo bash -c "\
            apt-get update && \
            apt-get install -y dirmngr gnupg apt-transport-https ca-certificates software-properties-common curl && \
            gpg --homedir /tmp --batch --yes --no-default-keyring --keyring /usr/share/keyrings/mono-official-archive-keyring.gpg --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF && \
            echo 'deb [signed-by=/usr/share/keyrings/mono-official-archive-keyring.gpg] https://download.mono-project.com/repo/ubuntu stable-focal main' > /etc/apt/sources.list.d/mono-official-stable.list && \
            mkdir -p /etc/apt/keyrings && \
            curl -fsSL https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key | gpg --batch --yes --dearmor -o /etc/apt/keyrings/nodesource.gpg && \
            echo 'deb [signed-by=/etc/apt/keyrings/nodesource.gpg] https://deb.nodesource.com/node_20.x nodistro main' > /etc/apt/sources.list.d/nodesource.list && \
            apt-get update && \
            apt-get install -y wget build-essential zip unzip tar git xz-utils nodejs
          "
        # Deps only involved on AMD64 architecture
      - name: Install x64 deps
        if: matrix.arch == 'x64' && !endsWith(matrix.template, '-docker')
        run: |
          sudo bash -c "\
            dpkg --add-architecture i386 && \
            echo steam steam/question select \"I AGREE\" | debconf-set-selections && \
            echo steam steam/license note '' | debconf-set-selections && \
            apt update && \
            apt install -y lib32gcc-s1 libstdc++6 libstdc++6:i386 libcurl3-gnutls:i386
          "
        # Add our user to the pufferpanel group so we can kick off our binary
      - name: Create user
        run: |
          getent group pufferpanel ||sudo groupadd pufferpanel
          sudo usermod -a -G pufferpanel $USER

      - name: AppArmor nonsense
        run: |
          echo -e "abi <abi/3.0>, \ninclude <tunables/global> \n$(pwd)/templatetester_${{ matrix.arch }} flags=(unconfined) {n}" > sudo tee /etc/apparmor.d/templatetester
          echo -e "abi <abi/3.0>, \ninclude <tunables/global> \n$(pwd)/pufferpanel_${{ matrix.arch }} flags=(unconfined) {\n}" > sudo tee /etc/apparmor.d/pufferpanel
          sudo bash -c \"
            apparmor_parser -r /etc/apparmor.d/templatetester && \
            apparmor_parser -r /etc/apparmor.d/pufferpanel
          "

        # Run the tester on the template provided
      - name: Run
        run: |
          chmod +x pufferpanel_* templatetester_*
          ./templatetester_${{ matrix.arch }} --skip=* --require=${{ matrix.template }} --binary=$(pwd)/pufferpanel_${{ matrix.arch }}

      - name: Cleanup
        run: |
          sudo bash -c \"
              apparmor_parser -R /etc/apparmor.d/templatetester && \
              apparmor_parser -R /etc/apparmor.d/pufferpanel && \
              rm -f /etc/apparmor.d/templatetester /etc/apparmor.d/pufferpanel
            "