name: Build Tool - Tester
on:
  workflow_dispatch:
    inputs:
      no-run-tool:
        description: 'Skips running of the tool'
        default: false
        required: true
        type: boolean

env:
  SWAG_VERSION: "1.16.4"
  NODE_VERSION: "22"

jobs:
  build-tool:
    name: Build Tool
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'yarn'
          cache-dependency-path: 'client/yarn.lock'

      - name: Restore Go BIN
        id: restore-go-bin
        uses: actions/cache@v4
        with:
          path: |
            ~/go/bin
          key: ${{ runner.os }}-swag-${{ env.SWAG_VERSION }}
          restore-keys: |
            ${{ runner.os }}-swag-

      - name: Download Go Binaries
        if: steps.restore-go-bin.outputs.cache-hit != 'true'
        run: |
          wget https://github.com/swaggo/swag/releases/download/v${{ env.SWAG_VERSION }}/swag_${{ env.SWAG_VERSION }}_Linux_x86_64.tar.gz
          mkdir -p ~/go/bin
          tar -zxf swag*.tar.gz -C ~/go/bin
          rm -rf swag*.tar.gz
          
      - name: Set CurseForge Key
        env:
          secret_set: ${{ secrets.CURSEFORGE_CODE }}
        if: ${{ env.secret_set != '' }}
        run: |
          echo '${{ secrets.CURSEFORGE_CODE }}' > config/curseforge.go

      - name: Download Go modules
        run: |
          go mod download

      - name: Generate Swagger Docs
        run: |
          ~/go/bin/swag init --md . -o web/swagger -g web/loader.go

      - name: yarn install, build
        run: |
          npm install -g yarn
          yarn install
          env VITE_CHECK_ENV="true" yarn build
        env:
          CI: true
        working-directory: client
          
      - name: Download APT packages
        run: |
          sudo apt-get update
          sudo apt-get install --download-only -y gcc-aarch64-linux-gnu

      - name: APT Install
        run: |
          sudo apt-get install -y gcc-aarch64-linux-gnu

      - name: Prep
        run: |
          mkdir build-artifacts

      - name: Build AMD64
        run: |
          go build -o build-artifacts/pufferpanel_x64 -v github.com/pufferpanel/pufferpanel/v3/cmd
          go build -o build-artifacts/templatetester_x64 -v github.com/pufferpanel/pufferpanel/v3/tools/templatetester
        env:
          GOOS: linux
          GOARCH: amd64

      - name: Build ARM64
        run: |
          go build -o build-artifacts/pufferpanel_arm64 -v github.com/pufferpanel/pufferpanel/v3/cmd
          go build -o build-artifacts/templatetester_arm64 -v github.com/pufferpanel/pufferpanel/v3/tools/templatetester
        env:
          GOOS: linux
          GOARCH: arm64
          CC: aarch64-linux-gnu-gcc
          CGO_ENABLED: 1

      - name: Generate job artifact
        uses: actions/upload-artifact@v4
        with:
          name: tool-binaries
          path: build-artifacts/
          if-no-files-found: error

      - name: Get templates
        run: |
          build-artifacts/templatetester_x64 --print
          cat $GITHUB_ENV

      - name: Show ENV
        run: |
          printf '%s\n' "$TEMPLATES"

      - name: Trigger tests
        id: trigger
        if: ${{ ! inputs.no-run-tool }}
        uses: peter-evans/repository-dispatch@v2
        with:
          event-type: template-tester
          client-payload: '{ "templates": [ ${{ env.TEMPLATES }} ], "run_id": "${{ github.run_id }}" }'